import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useCoins } from "../hooks";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [shouldFetch, setShouldFetch] = useState<boolean>(false);

  const { data, error } = useCoins(shouldFetch);

  if (error) console.log("error", error);

  console.log("data", data);

  useEffect(() => {
    setShouldFetch(true);

    const apiKey = "coinrankingffe328d3b6e13fedf28f8c1840276a7fdc3115986410d1e7";
    const url = "https://api.coinranking.com/v2/coins";
    const resultsContainer = document.getElementById("results");
    const queryString = new URLSearchParams({
      "x-access-token": apiKey,
      search: "Bit",
    });

    fetch(`${url}?${queryString}`, { mode: "no-cors" })
      .then((response) => response.json())
      .then((response) => {
        console.log("response", response);

        if (response.status === "success") {
          const html = response.data.coins.map(
            (coin) => `
        <tr>
          <td>${coin.rank}</td>
          <td>${coin.name}</td>
          <td>${coin.price}</td>
        </tr>
      `
          );

          resultsContainer.innerHTML = html.join("");
        } else {
          // Show error message if the request failed
          resultsContainer.innerHTML = `<tr><td colspan="3">${response.message}</td></tr>`;
        }
      })
      .catch((error) => {
        console.error(error);
      });
  }, []);

  return (
    <div className={styles.container}>
      <div id="results"></div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card}>
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
